{% set name = "face" %}
{% set version = "26.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: ae12136ff0052f124811f5319670a8d9d29b7d2caaaabe542813690967cc6bca

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - boltons >=20.0.0
    - python >={{ python_min }}

test:
  imports:
    - face
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mahmoud/face
  doc_url: https://python-face.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A command-line interface parser and framework, friendly for users, full-featured for developers."

extra:
  recipe-maintainers:
    - CJ-Wright
    - thewchan
