{% set name = "face" %}
{% set version = "20.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7d59ca5ba341316e58cf72c6aff85cca2541cf5056c4af45cb63af9a814bed3e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - boltons
    - python

test:
  imports:
    - face

about:
  home: "https://github.com/mahmoud/face"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "LICENSE"
  summary: "A command-line interface parser and framework, friendly for users, full-featured for developers."

extra:
  recipe-maintainers:
    - CJ-Wright
