{% set name = "face" %}
{% set version = "22.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5d692f90bc8f5987b636e47e36384b9bbda499aaf0a77aa0b0bbe834c76923d

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - boltons
    - python

test:
  imports:
    - face

about:
  home: https://github.com/mahmoud/face
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A command-line interface parser and framework, friendly for users, full-featured for developers.

extra:
  recipe-maintainers:
    - CJ-Wright
