{% set name = "face" %}
{% set version = "24.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 611e29a01ac5970f0077f9c577e746d48c082588b411b33a0dd55c4d872949f6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - boltons
    - python

test:
  imports:
    - face

about:
  home: "https://github.com/mahmoud/face"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "LICENSE"
  summary: "A command-line interface parser and framework, friendly for users, full-featured for developers."

extra:
  recipe-maintainers:
    - CJ-Wright
