schema_version: 1

context:
  name: face
  version: 26.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ae12136ff0052f124811f5319670a8d9d29b7d2caaaabe542813690967cc6bca

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - boltons >=20.0.0
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - face
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A command-line interface parser and framework, friendly for users, full-featured for developers.
  homepage: https://github.com/mahmoud/face
  documentation: https://python-face.readthedocs.io/

extra:
  recipe-maintainers:
    - CJ-Wright
    - thewchan
